name: Benchmark

on:
  push:
    branches:
      - benchmark

jobs:
  build_linux_binary:
    name: Build Linux binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build static binary
      run: |
        sudo chown -R 1000:1000 .
        docker run --rm -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder:stable \
          cargo build --release
        sudo chown -R $(whoami):$(whoami) .
    - name: Compress binary using UPX
      run: |
        sudo apt-get install -y upx
        upx target/x86_64-unknown-linux-musl/release/frum
    - uses: actions/upload-artifact@v2
      with:
        name: frum-linux
        path: target/x86_64-unknown-linux-musl/release/frum

  benchmark_on_linux:
    name: Benchmark (Linux)
    needs: [build_linux_binary]
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_benchmark_workflows
        with:
          route: GET /repos/:repository/actions/runs
          repository: ${{ github.repository }}
          branch: benchmark
          status: completed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/${{ github.repository_owner }}/${{ github.repository }}/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Take the output
        run: |
          URL=$(echo '${{ steps.get_latest_release.outputs.data }}' | jq -r '.assets | map(select(.name | endswith("x86_64-unknown-linux-musl.tar.gz"))) | .[0].browser_download_url')
          curl -L $URL -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' > /tmp/frum-latest.zip
          mkdir ~/.frum-latest
          unzip -d ~/.frum-latest /tmp/frum-latest.zip
          ls -lah ~/.frum-latest
      - uses: actions/checkout@v2
      - name: Install hyperfine
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.10.0/hyperfine_1.10.0_amd64.deb
          sudo dpkg -i hyperfine_1.10.0_amd64.deb
      - name: Install rbenv
        run: |
          git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
          git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
      - uses: actions/download-artifact@v2
        with:
          name: frum-linux
          path: target/release/
      - name: Run benchmarks
        run: ./benchmarks/run

      - name: Read basic.md for the generated report
        id: basic_result
        uses: juliangruber/read-file-action@v1
        with:
          path: benchmarks/results/basic.md

      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/commits/:commit_sha/comments
          repository: ${{ github.repository }}
          commit_sha: ${{ github.sha }}
          body: |
            |
            ${{ steps.basic_result.outputs.content }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
